version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '5050:5050'
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend:5050
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:5050
networks:
  app-network:
