version: '3.8'

services:
  backend:
    build: ./../backend
    ports:
      - "5050:5050"
      
  frontend:
    build: ./../frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

